# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 0.0.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - dev

  # blacklist
  except:
    - gh-pages

# environment variables
environment:
  VERSION_BRANCH: $(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  PROJECT_NAME: WindowsFirewallDashboard
  ARTIFACT_PROJECT_NAME: WindowsFirewallDashboard
  ARTIFACT_NAME: WindowsFirewallDashboard
  GITHUB_TAG_NAME_BRANCH_DEV: v$(APPVEYOR_BUILD_VERSION)-dev
  GITHUB_TAG_NAME_BRANCH_MASTER: v$(APPVEYOR_BUILD_VERSION)
  GITHUB_TOKEN_ENCRYPTED: nRaKUqfN0jThBJ38Qrhex0gGoicQZpBuMfmDZ03A4NEQN5AGoqObtBZu6iKq3D5I

# Do not build on tags (GitHub only)
skip_tags: true

# Skipping commits with particular message or from user
#skip_commits:

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os:
  - Visual Studio 2015
#  - Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
#clone_folder: c:\projects\myproject

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

# scripts that run after cloning repository
# use - ps for powershell, - cmd for commandline
install:
  - cmd: nuget restore
#  - cmd: cmake --version
#  - cmd: msbuild /version

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release

build:
  parallel: true                   # enable MSBuild parallel builds
  project: $(PROJECT_NAME).sln     # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal                # quiet|minimal|normal|detailed

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
#build_script:

# to disable automatic builds
#build: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: $(PROJECT_NAME)\bin\$(CONFIGURATION)\
    name: $(ARTIFACT_NAME)

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, GitHub, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  # Development branch, deploy to github
  - provider: GitHub
    auth_token:
      secure: nRaKUqfN0jThBJ38Qrhex0gGoicQZpBuMfmDZ03A4NEQN5AGoqObtBZu6iKq3D5I
    tag: $(GITHUB_TAG_NAME_BRANCH_DEV)
    release: $(GITHUB_TAG_NAME_BRANCH_DEV)
    # description needs to be declared, but can be empty, so that github not reject the deploy
    description: "This is a development release. It should not be used in production environments."
    artifact: $(ARTIFACT_NAME)
    draft: false
    prerelease: true
    on:
      branch: dev                    # release from dev branch only
#      branch: appveyor_test          # todo: delete
      appveyor_repo_tag: false       # deploy on tag push only; default: true
  # Master branch, deploy to github
  - provider: GitHub
    auth_token:
      secure: nRaKUqfN0jThBJ38Qrhex0gGoicQZpBuMfmDZ03A4NEQN5AGoqObtBZu6iKq3D5I
    tag: $(GITHUB_TAG_NAME_BRANCH_MASTER)
    release: $(GITHUB_TAG_NAME_BRANCH_MASTER)
    # description needs to be declared, but can be empty, so that github not reject the deploy
    description: ""
    artifact: $(ARTIFACT_NAME)
    draft: false
    prerelease: false
    on:
      branch: master                 # release from dev branch only
      appveyor_repo_tag: false       # deploy on tag push only; default: true


# to disable deployment
#deploy: off

# scripts to run before deployment
before_deploy:
#  - ps: Get-ChildItem Env:*
#  - ps: ls "${Env:PROJECT_NAME}\bin"
#  - ps: ls "${Env:PROJECT_NAME}\bin\${Env:configuration}"

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
# on_success:
#   - do something

# on build failure
# on_failure:
#   - do something

# after build failure or success
# on_finish:
#   - do something